FROM openjdk:11-jre-slim

MAINTAINER lmussi

VOLUME /tmp
ADD superheroes.jar /opt/superheroes/
EXPOSE 8080
WORKDIR /opt/superheroes/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "superheroes.jar"]
